// Copyright 2026 Blink Labs Software
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

import (
	"bytes"
	"embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"mime"
	"net"
	"net/http"
	"runtime/debug"
	"strings"
	"time"

	ouroboros "github.com/blinklabs-io/gouroboros"
	"github.com/blinklabs-io/gouroboros/protocol/localtxmonitor"
	"github.com/blinklabs-io/gouroboros/protocol/localtxsubmission"
	_ "github.com/blinklabs-io/tx-submit-api/docs" // docs is generated by Swag CLI
	"github.com/blinklabs-io/tx-submit-api/internal/config"
	"github.com/blinklabs-io/tx-submit-api/internal/logging"
	"github.com/blinklabs-io/tx-submit-api/internal/metrics"
	"github.com/blinklabs-io/tx-submit-api/submit"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	httpSwagger "github.com/swaggo/http-swagger"
)

//go:embed static
var staticFS embed.FS

// maxTxBodyBytes is the maximum accepted request body size for transaction
// submission. Cardano's protocol limit is ~16KB; 64KB gives ample overhead.
const maxTxBodyBytes = 64 * 1024

// corsMiddleware adds CORS headers allowing all origins.
func corsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Accept, hx-current-url, hx-request, hx-target, hx-trigger")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// responseWriter wraps http.ResponseWriter to capture status and size for logging.
type responseWriter struct {
	http.ResponseWriter
	status int
	size   int
}

func (rw *responseWriter) WriteHeader(status int) {
	rw.status = status
	rw.ResponseWriter.WriteHeader(status)
}

func (rw *responseWriter) Write(b []byte) (int, error) {
	n, err := rw.ResponseWriter.Write(b)
	rw.size += n
	return n, err
}

// Unwrap allows callers to detect optional interfaces (http.Flusher, http.Hijacker, etc.)
// through the responseWriter wrapper.
func (rw *responseWriter) Unwrap() http.ResponseWriter {
	return rw.ResponseWriter
}

func loggingMiddleware(skipPaths []string) func(http.Handler) http.Handler {
	skip := make(map[string]struct{}, len(skipPaths))
	for _, p := range skipPaths {
		skip[p] = struct{}{}
	}
	logger := logging.GetLogger().With("type", "access")
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()
			rw := &responseWriter{ResponseWriter: w, status: http.StatusOK}
			next.ServeHTTP(rw, r)
			if _, ok := skip[r.URL.Path]; ok {
				return
			}
			logger.Info("request completed",
				"status", rw.status,
				"method", r.Method,
				"path", r.URL.Path,
				"query", r.URL.RawQuery,
				"ip", r.RemoteAddr,
				"userAgent", r.UserAgent(),
				"latency", time.Since(start).String(),
				"size", rw.size,
			)
		})
	}
}

func recoveryMiddleware(next http.Handler) http.Handler {
	logger := logging.GetLogger()
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if err := recover(); err != nil {
				logger.Error("panic recovered",
					"err", err,
					"stack", string(debug.Stack()),
				)
				http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
			}
		}()
		next.ServeHTTP(w, r)
	})
}

// newMux creates the API ServeMux. Used by Start and tests to avoid route drift.
func newMux(fsys fs.FS) *http.ServeMux {
	mux := http.NewServeMux()

	// Static UI
	mux.Handle("/ui/", http.StripPrefix("/ui", http.FileServer(http.FS(fsys))))
	// Redirect root to /ui
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}
		http.Redirect(w, r, "/ui", http.StatusMovedPermanently)
	})

	mux.HandleFunc("GET /healthcheck", handleHealthcheck)
	// Swagger UI
	mux.Handle("/swagger/", httpSwagger.WrapHandler)

	// API routes
	mux.HandleFunc("POST /api/submit/tx", handleSubmitTx)
	mux.HandleFunc("GET /api/hastx/{tx_hash}", handleHasTx)

	return mux
}

func writeJSON(w http.ResponseWriter, status int, data any) {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(data); err != nil {
		logging.GetLogger().Error("failed to encode JSON response", "err", err)
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_, _ = buf.WriteTo(w)
}

// @title			tx-submit-api
// @version		v0
// @description	Cardano Transaction Submit API
// @BasePath		/
// @contact.name	Blink Labs Software
// @contact.url	https://blinklabs.io
// @contact.email	support@blinklabs.io
//
// @license.name	Apache 2.0
// @license.url	http://www.apache.org/licenses/LICENSE-2.0.html
func Start(cfg *config.Config) error {
	// Standard logging
	logger := logging.GetLogger()
	if cfg.Tls.CertFilePath != "" && cfg.Tls.KeyFilePath != "" {
		logger.Info(
			"starting API TLS listener",
			"address", cfg.Api.ListenAddress,
			"port", cfg.Api.ListenPort,
		)
	} else {
		logger.Info(
			"starting API listener",
			"address", cfg.Api.ListenAddress,
			"port", cfg.Api.ListenPort,
		)
	}

	// Configure static file serving
	fsys, err := fs.Sub(staticFS, "static")
	if err != nil {
		return err
	}

	mux := newMux(fsys)

	skipPaths := []string{}
	if !cfg.Logging.Healthchecks {
		skipPaths = append(skipPaths, "/healthcheck")
	}
	var handler http.Handler = mux
	handler = loggingMiddleware(skipPaths)(handler)
	handler = recoveryMiddleware(handler)
	handler = corsMiddleware(handler)

	metrics.Register()

	// Start metrics listener
	go func() {
		logger.Info("starting metrics listener",
			"address", cfg.Metrics.ListenAddress,
			"port", cfg.Metrics.ListenPort)
		metricsMux := http.NewServeMux()
		metricsMux.Handle("/", promhttp.Handler())
		metricsServer := &http.Server{
			Addr:         fmt.Sprintf("%s:%d", cfg.Metrics.ListenAddress, cfg.Metrics.ListenPort),
			Handler:      metricsMux,
			ReadTimeout:  10 * time.Second,
			WriteTimeout: 10 * time.Second,
			IdleTimeout:  120 * time.Second,
		}
		if err := metricsServer.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logger.Error("metrics listener failed", "err", err)
		}
	}()

	addr := fmt.Sprintf("%s:%d", cfg.Api.ListenAddress, cfg.Api.ListenPort)
	server := &http.Server{
		Addr:         addr,
		Handler:      handler,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 60 * time.Second,
		IdleTimeout:  120 * time.Second,
	}
	if cfg.Tls.CertFilePath != "" && cfg.Tls.KeyFilePath != "" {
		err = server.ListenAndServeTLS(cfg.Tls.CertFilePath, cfg.Tls.KeyFilePath)
	} else {
		err = server.ListenAndServe()
	}
	if errors.Is(err, http.ErrServerClosed) {
		return nil
	}
	return err
}

func handleHealthcheck(w http.ResponseWriter, _ *http.Request) {
	// TODO: add some actual health checking here
	writeJSON(w, http.StatusOK, map[string]bool{"failed": false})
}

// handleHasTx godoc
//
//	@Summary		HasTx
//	@Description	Determine if a given transaction ID exists in the node mempool.
//	@Produce		json
//	@Param			tx_hash	path		string	true	"Transaction Hash"
//	@Success		200		{object}	string	"Ok"
//	@Failure		400		{object}	string	"Bad Request"
//	@Failure		404		{object}	string	"Not Found"
//	@Failure		415		{object}	string	"Unsupported Media Type"
//	@Failure		500		{object}	string	"Server Error"
//	@Router			/api/hastx/{tx_hash} [get]
func handleHasTx(w http.ResponseWriter, r *http.Request) {
	// First, initialize our configuration and loggers
	cfg := config.GetConfig()
	logger := logging.GetLogger()

	txHash := r.PathValue("tx_hash")
	if txHash == "" {
		writeJSON(w, http.StatusBadRequest, "missing transaction hash")
		return
	}

	// Decode hex string to raw hash bytes expected by the LocalTxMonitor protocol.
	txHashBytes, err := hex.DecodeString(txHash)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, "invalid transaction hash: must be hex-encoded")
		return
	}

	// Connect to cardano-node and check for transaction
	timeout := time.Duration(cfg.Node.Timeout) * time.Second //nolint:gosec
	oConn, err := submit.DialNode(
		uint32(cfg.Node.NetworkMagic),
		cfg.Node.Address,
		cfg.Node.Port,
		cfg.Node.SocketPath,
		ouroboros.WithLocalTxMonitorConfig(
			localtxmonitor.NewConfig(
				localtxmonitor.WithAcquireTimeout(timeout),
				localtxmonitor.WithQueryTimeout(timeout),
			),
		),
	)
	if err != nil {
		logger.Error("failure communicating with node", "err", err)
		writeJSON(w, http.StatusInternalServerError, "failure communicating with node")
		return
	}
	defer oConn.Close()

	hasTx, err := oConn.LocalTxMonitor().Client.HasTx(txHashBytes)
	if err != nil {
		logger.Error("failure getting transaction", "err", err)
		writeJSON(w, http.StatusInternalServerError,
			fmt.Sprintf("failure getting transaction: %s", err))
		return
	}
	if !hasTx {
		writeJSON(w, http.StatusNotFound, "transaction not found in mempool")
		return
	}
	writeJSON(w, http.StatusOK, "transaction found in mempool")
}

// handleSubmitTx godoc
//
//	@Summary		Submit Tx
//	@Description	Submit an already serialized transaction to the network.
//	@Description	Returns 202 Accepted once the local node has confirmed the transaction
//	@Description	is in its mempool (AcceptTx received synchronously). A 202 response
//	@Description	means the node accepted it locally; propagation across the network is
//	@Description	not guaranteed by this API.
//	@Produce		json
//	@Param			Content-Type	header		string	true	"Content type"	Enums(application/cbor)
//	@Success		202				{object}	string	"Transaction accepted into node mempool"
//	@Failure		400				{object}	string	"Bad Request"
//	@Failure		415				{object}	string	"Unsupported Media Type"
//	@Failure		500				{object}	string	"Server Error"
//	@Router			/api/submit/tx [post]
func handleSubmitTx(w http.ResponseWriter, r *http.Request) {
	cfg := config.GetConfig()
	logger := logging.GetLogger()
	clientIP := realClientIP(r, cfg.Api.TrustedProxies)

	// Check our headers for content-type. Wrong content-type is rejected before
	// reading the body, so no IP metric is recorded here.
	mediaType, _, _ := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if mediaType != "application/cbor" {
		logger.Error("invalid request body, should be application/cbor")
		writeJSON(w, http.StatusUnsupportedMediaType, "invalid request body, should be application/cbor")
		metrics.IncTxSubmitFailCount()
		return
	}

	// Read raw transaction bytes, capped at maxTxBodyBytes to prevent unbounded allocation.
	txRawBytes, err := io.ReadAll(http.MaxBytesReader(w, r.Body, maxTxBodyBytes))
	if err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			logger.Error("request body too large", "limit", maxTxBodyBytes)
			writeJSON(w, http.StatusRequestEntityTooLarge, "request body too large")
		} else {
			logger.Error("failed to read request body", "err", err)
			writeJSON(w, http.StatusInternalServerError, "failed to read request body")
		}
		metrics.IncTxSubmitFailCount()
		metrics.RecordTxRequest("error")
		return
	}

	// Parse tx content signals before submitting — best-effort, never blocks submission.
	txInfo, err := submit.ParseTxInfo(txRawBytes)
	if err != nil {
		logger.Warn("failed to parse tx content signals", "err", err, "ip", clientIP)
		txInfo = nil
	}

	// Send TX
	errorChan := make(chan error, 1)
	submitConfig := &submit.Config{
		ErrorChan:    errorChan,
		NetworkMagic: cfg.Node.NetworkMagic,
		NodeAddress:  cfg.Node.Address,
		NodePort:     cfg.Node.Port,
		SocketPath:   cfg.Node.SocketPath,
		Timeout:      cfg.Node.Timeout,
	}
	txHash, err := submit.SubmitTx(submitConfig, txRawBytes)
	if err != nil {
		var txRejectErr *localtxsubmission.TransactionRejectedError
		isRejected := errors.As(err, &txRejectErr)
		if r.Header.Get("Accept") == "application/cbor" {
			if isRejected && txRejectErr != nil {
				w.Header().Set("Content-Type", "application/cbor")
				w.WriteHeader(http.StatusBadRequest)
				_, _ = w.Write(txRejectErr.ReasonCbor)
			} else {
				w.Header().Set("Content-Type", "application/cbor")
				w.WriteHeader(http.StatusInternalServerError)
				_, _ = w.Write([]byte{})
			}
		} else {
			writeJSON(w, http.StatusBadRequest, err.Error())
		}
		result := "error"
		if isRejected {
			result = "rejected"
		}
		metrics.IncTxSubmitFailCount()
		metrics.RecordTxRequest(result)
		if txInfo != nil {
			metrics.RecordTxContent(txInfo.ScriptType, txInfo.HasMinting, txInfo.HasReferenceInputs)
		}
		return
	}

	// Node confirmed the tx is in its mempool (AcceptTx received synchronously).
	// Record success before responding so metrics always agree with the HTTP status.
	metrics.IncTxSubmitCount()
	metrics.RecordTxRequest("accepted")
	if txInfo != nil {
		metrics.RecordTxContent(txInfo.ScriptType, txInfo.HasMinting, txInfo.HasReferenceInputs)
	}
	writeJSON(w, http.StatusAccepted, txHash)

	// Drain errorChan in the background. Post-submission connection errors do not
	// change the metric outcome — the tx is already in the mempool — but we log
	// them for operational visibility.
	go func() {
		select {
		case err, ok := <-errorChan:
			if ok {
				logger.Error("post-submission connection error", "err", err)
			}
		case <-time.After(time.Duration(cfg.Node.Timeout) * time.Second): //nolint:gosec
		}
	}()
}

// realClientIP extracts the client IP from the request. Forwarded headers
// (X-Real-IP, X-Forwarded-For) are only trusted when the immediate peer
// (r.RemoteAddr) is in the trustedProxies list; otherwise RemoteAddr is used
// directly to prevent IP spoofing by untrusted callers.
func realClientIP(r *http.Request, trustedProxies []string) string {
	// Parse the immediate peer IP from RemoteAddr.
	peerHost, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		peerHost = r.RemoteAddr
	}
	peerIP := net.ParseIP(peerHost)

	// Only honour forwarded headers when the peer is a trusted proxy.
	if peerIP != nil {
		for _, cidr := range trustedProxies {
			var trusted net.IP
			var network *net.IPNet
			if strings.Contains(cidr, "/") {
				_, network, err = net.ParseCIDR(cidr)
				if err != nil {
					continue
				}
			} else {
				trusted = net.ParseIP(cidr)
			}
			inRange := (network != nil && network.Contains(peerIP)) ||
				(trusted != nil && trusted.Equal(peerIP))
			if inRange {
				if ip := strings.TrimSpace(r.Header.Get("X-Real-IP")); ip != "" {
					if parsed := net.ParseIP(ip); parsed != nil {
						return parsed.String()
					}
				}
				if forwarded := r.Header.Get("X-Forwarded-For"); forwarded != "" {
					first, _, _ := strings.Cut(forwarded, ",")
					if parsed := net.ParseIP(strings.TrimSpace(first)); parsed != nil {
						return parsed.String()
					}
				}
				break
			}
		}
	}

	return peerHost
}
