basePath: /
info:
  contact:
    email: support@blinklabs.io
    name: Blink Labs
    url: https://blinklabs.io
  description: Cardano Transaction Submit API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: tx-submit-api
  version: v0
paths:
  /api/hastx/{tx_hash}:
    get:
      description: Determine if a given transaction ID exists in the node mempool.
      parameters:
      - description: Transaction Hash
        in: path
        name: tx_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "415":
          description: Unsupported Media Type
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: HasTx
  /api/submit/tx:
    post:
      description: Submit an already serialized transaction to the network.
      parameters:
      - description: Content type
        enum:
        - application/cbor
        in: header
        name: Content-Type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "415":
          description: Unsupported Media Type
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Submit Tx
schemes:
- http
swagger: "2.0"
