basePath: /
host: localhost:8090
info:
  contact:
    email: support@cloudstruct.net
    name: CloudStruct
    url: https://cloudstruct.net
  description: Cardano Submit API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: go-cardano-submit-api
  version: 3.1.0
paths:
  /api/submit/tx:
    post:
      description: Submit an already serialized transaction to the network.
      parameters:
      - description: Content type
        enum:
        - application/cbor
        in: header
        name: Content-Type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Submit Tx
schemes:
- http
swagger: "2.0"
